#!/bin/bash
#
# NVR szerver oldal
#
#

# nap sorszáma
DNOW=$(date +%w)

# alapadatok
FILEDAY="./nvr.day.$DNOW"
FILECAMSTAT="../seccam/nvr.run"
CAM_START=("/etc/motion/c1-start" "/etc/motion/c2-start" "/etc/motion/c3-start")
CAM_STOP=("/etc/motion/c1-stop" "/etc/motion/c2-stop" "/etc/motion/c3-stop")
CAM_RESTART="/etc/motion/c-restart"
CAM_ALL_START="/etc/motion/c-allstart"
CAM_ALL_STOP="/etc/motion/c-allstop"

# változásfigyelés: másodperc
CHANGEDETECTINT=300

# dátum
D=$(date)
START="0"
if [ -f $FILEDAY ]; then
	# if [ $(( $(date +%s) - $(date +%s -r $FILEDAY) )) -le $CHANGEDETECTINT ]; then
	# fi
	. $FILEDAY
	T=$(date +%H%M)
	if [ "$T" -gt "$CAM_NIGHT_STOP" ] && [ "$T" -lt "$CAM_NIGHT_START" ]; then
		START="1"
	fi
	if [ "$T" -gt "$CAM_DAY_START" ] && [ "$T" -lt "$CAM_DAY_STOP" ]; then
		START="1"
	fi
	#else
	#	echo $D - nem változott
	#fi
fi

if [ "$START" = "1" ]; then
	echo $D - kamerák intervallumon belül
else
	echo $D - kamerák intervallumon kívül
fi

# indítás - leállítás
if [ -f $FILECAMSTAT ]; then
	. $FILECAMSTAT
	if [ "$CAM_DETECT" = "0" ]; then
		echo $D - kamerák leállítása
		${CAM_ALLSTOP} 2>>/dev/null
	else
		#echo $D - kamerák engedélyezve
		if [ "$START" = "1" ]; then
			echo $D - kamerák indítása
			for i in ${!CAM_ENABLE[@]}; do
				if [ ! ${CAM_ENABLE[$i]} -eq "0" ]; then
					#echo start $i
					${CAM_START[$i]} 2>>/dev/null
				else
					#echo stop $i
					${CAM_STOP[$i]} 2>>/dev/null
				fi
			done
			${CAM_RESTART} 2>>/dev/null
		else
			echo $D - kamerák leállítása
			${CAM_ALLSTOP} 2>>/dev/null
		fi
	fi
fi

#
