#!/bin/bash
#
# NVR szerver oldal
#
# cron fájl létrehozás
#

# nap sorszáma
DNOW=$(date +%w)

# alapadatok
FILEDAY="./nvr.day.$DNOW"
FILECAMSTAT="./nvr.run"
CAM_START=("/etc/motion/c1-start" "/etc/motion/c2-start" "/etc/motion/c3-start")
CAM_STOP=("/etc/motion/c1-stop" "/etc/motion/c2-stop" "/etc/motion/c3-stop")
CAM_RESTART="/etc/motion/c-restart"
CAM_ALL_START="/etc/motion/c-allstart"
CAM_ALL_STOP="/etc/motion/c-allstop"

#CRON_FILE="/etc/cron.d/seccam"
CRON_FILE="./seccam.cron"

# változásfigyelés: másodperc
CHANGEDETECTINT=300

# dátum
D=$(date)
START="0"
if [ -f $FILEDAY ]; then
	 #if [ $(( $(date +%s) - $(date +%s -r $FILEDAY) )) -le $CHANGEDETECTINT ]; then
		. $FILEDAY
		T=$(date +%H%M)
		START="1"
		NSTARTH=$(date -d "$CAM_NIGHT_START" +'%H')
		NSTARTM=$(date -d "$CAM_NIGHT_START" +'%M')
		NSTOPH=$(date -d "$CAM_NIGHT_STOP" +'%H')
		NSTOPM=$(date -d "$CAM_NIGHT_STOP" +'%M')
		DSTARTH=$(date -d "$CAM_DAY_START" +'%H')
		DSTARTM=$(date -d "$CAM_DAY_START" +'%M')
		DSTOPH=$(date -d "$CAM_DAY_STOP" +'%H')
		DSTOPM=$(date -d "$CAM_DAY_STOP" +'%M')
		#echo $NSTARTH:$NSTARTM $NSTOPH:$NSTOPM $DSTARTH:$DSTARTM $DSTOPH:$DSTOPM
		echo "#" >$CRON_FILE
		echo "$NSTARTM $NSTARTH * * * root $CAM_ALL_START" >>$CRON_FILE
		echo "$NSTOPM $NSTOPH * * * root $CAM_ALL_STOP" >>$CRON_FILE
		echo "$DSTARTM $DSTARTH * * * root $CAM_ALL_START" >>$CRON_FILE
		echo "$DSTOPM $DSTOPH * * * root $CAM_ALL_STOP" >>$CRON_FILE
		echo "#" >>$CRON_FILE
	#fi
fi

if [ "$START" = "1" ]; then
	echo $D - új cron fájl elkészítése
else
	echo $D - nincs változás
fi

# indítás - leállítás
if [ -f $FILECAMSTAT ]; then
	. $FILECAMSTAT
	if [ "$CAM_DETECT" = "0" ]; then
		echo $D - kamerák leállítása
		rm $CRON_FILE 2>>/dev/null
		${CAM_ALLSTOP} 2>>/dev/null
	else
		for i in ${!CAM_ENABLE[@]}; do
			if [ ! ${CAM_ENABLE[$i]} -eq "0" ]; then
				#echo start $i
				${CAM_START[$i]} 2>>/dev/null
			else
				#echo stop $i
				${CAM_STOP[$i]} 2>>/dev/null
			fi
		done
		${CAM_RESTART} 2>>/dev/null
		echo $D - kamerák beállítása
	fi
fi

#
