#!/bin/bash

# motion: minden kamera felvétel indítás
d=`date`
echo $d - Minden kamera indítása. >> /var/log/motion/cam.log

if [ ! -f /etc/motion/camera1.conf ]; then
    /etc/motion/c1-start
fi

if [ ! -f /etc/motion/camera2.conf ]; then
    /etc/motion/c2-start
fi

if [ ! -f /etc/motion/camera3.conf ]; then
    /etc/motion/c3-start
fi

#systemctl restart motion
killall motion 2>>/dev/null
motion & 2>>/dev/null

#
