#!/bin/bash

# kamera felvétel újraindítása

d=`date`
echo $d - Minden kamera újraindítása. >> /var/log/motion/cam.log

#systemctl restart motion

killall motion 2>>/dev/null
motion & 2>>/dev/null

#
